### ISSUE TITLE
get roads lengths in a city

### ISSUE THREAD

**Issue by HYuanggg** [JoaoCarabetta/osm-road-length#1]
* S2-py version:
* Python version: 3.7.7
* Operating System: windows 10

### Description

In you example code: you use wkt.loads() to create geometry and then get the roads lengths inside this geometry.
Could you also give some example of how to get the roads lengths inside a country?
Or I can only create some approximate geometry using latitudes and longitudes to do this?

**Comment by JoaoCarabetta** [comment]
Hi,

You can just create a rough wkt polygon of the country in an online tool.

This is the one that I usually use https://arthur-e.github.io/Wicket/sandbox-gmaps3.html

Let me know if it works

**Comment by HYuanggg** [comment]
Hi,
I first downloaded the coordinates data of a country from some website, but it didn't work well with so many latitudes and longitudes.
Then I changed your code from "Poly(hope I remember correctly)" to "area" and use a country's ID as the filter condition. It works for some countries and some cities but not for Germany. And the returned data is also kind of strange.

**Comment by JoaoCarabetta** [comment]
Do you have a reproducible test? I can take a look at it.

I never tried to use it on Europe, so I might have missed something.

**Comment by HYuanggg** [comment]
@JoaoCarabetta Sorry for a so late reply. I am not sure how to provide you a test, but if you have interest, you could have a look at this: https://github.com/HYuanggg/Use-OSM-Road-Length. In osm-road-length.ipynb is all I did.

**Comment by JoaoCarabetta** [comment]
Hey,

try to use this package to simplify your geometry:

https://pypi.org/project/rdp/

It may help

**Comment by HYuanggg** [comment]
@JoaoCarabetta Thanks, I will have a look at this.:D
